//------------------------------------------------------------------------
// Copyright(c) 2022 Castorid.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"NaiveGranular.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"NaiveGranular VST3 (64Bit)"
#else
#define stringFileDescription	"NaiveGranular VST3"
#endif
#define stringCompanyName		"Castorid\0"
#define stringLegalCopyright	"Copyright(c) 2022 Castorid."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
